#!/usr/bin/env python3
"""
Create a new Planet instance.

This script provisions all Cloudflare resources needed for a new planet instance,
similar to Rogue Planet's `rp init` command.

Usage:
    python scripts/create_instance.py --id planet-python --name "Planet Python"

This will:
1. Create config/instances/{id}.yaml from the template
2. Generate wrangler.{id}.jsonc for deployment
3. Print instructions for creating Cloudflare resources

For full automated provisioning, you'll need wrangler CLI installed.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

# Paths relative to script
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
CONFIG_DIR = PROJECT_ROOT / "config"
INSTANCES_DIR = CONFIG_DIR / "instances"
TEMPLATE_FILE = CONFIG_DIR / "instance.example.yaml"


def slugify(text: str) -> str:
    """Convert text to a valid slug for resource names."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    return text


def create_instance_config(
    instance_id: str,
    name: str,
    description: str,
    url: str,
    owner_name: str,
    owner_email: str,
    theme: str = "default",
) -> Path:
    """Create instance configuration file from template."""
    INSTANCES_DIR.mkdir(parents=True, exist_ok=True)

    config_content = f"""# Planet Instance Configuration: {name}
# Generated by create_instance.py

# =============================================================================
# Core Identity
# =============================================================================
planet:
  id: {instance_id}
  name: {name}
  description: {description}
  url: {url}
  owner:
    name: {owner_name}
    email: {owner_email}

# =============================================================================
# Branding & Theme
# =============================================================================
branding:
  # Available themes: default, classic, dark, minimal
  # Or path to custom theme directory
  theme: {theme}

  # User-Agent string for feed fetching
  user_agent: "{{name}}/1.0 (+{{url}}; {{email}})"

  # Footer text
  footer_text: "Powered by {{name}}"

  show_admin_link: true

# =============================================================================
# Content Settings
# =============================================================================
content:
  days: 7
  group_by_date: true
  max_entries_per_feed: 100
  retention_days: 90
  summary_max_length: 500

# =============================================================================
# Search Configuration
# =============================================================================
search:
  enabled: true
  embedding_max_chars: 2000
  score_threshold: 0.3
  top_k: 50

# =============================================================================
# Feed Processing
# =============================================================================
feeds:
  http_timeout_seconds: 30
  feed_timeout_seconds: 60
  auto_deactivate_threshold: 10
  failure_threshold: 3

# =============================================================================
# Authentication
# =============================================================================
auth:
  provider: github
  scopes:
    - user:email
  session_ttl_seconds: 604800

# =============================================================================
# Cloudflare Resources (auto-generated names)
# =============================================================================
cloudflare:
  database_name: {instance_id}-db
  vectorize_index: {instance_id}-entries
  feed_queue: {instance_id}-feed-queue
  dead_letter_queue: {instance_id}-feed-dlq

# =============================================================================
# Admin Users
# =============================================================================
admins:
  - username: your-github-username
    display_name: Your Name
"""

    config_path = INSTANCES_DIR / f"{instance_id}.yaml"
    config_path.write_text(config_content)
    return config_path


def generate_wrangler_config(
    instance_id: str,
    name: str,
    description: str,
    url: str,
    owner_name: str,
    owner_email: str,
    theme: str = "default",
    database_id: str = "YOUR_DATABASE_ID",
) -> Path:
    """Generate wrangler configuration file for the instance."""
    config = {
        "$schema": "node_modules/wrangler/config-schema.json",
        "name": instance_id,
        "main": "src/main.py",
        "compatibility_date": "2026-01-01",
        "compatibility_flags": ["python_workers", "python_dedicated_snapshot"],
        "limits": {"cpu_ms": 60000},
        "vars": {
            "PLANET_ID": instance_id,
            "PLANET_NAME": name,
            "PLANET_DESCRIPTION": description,
            "PLANET_URL": url,
            "PLANET_OWNER_NAME": owner_name,
            "PLANET_OWNER_EMAIL": owner_email,
            "THEME": theme,
            "RETENTION_DAYS": "90",
            "RETENTION_MAX_ENTRIES_PER_FEED": "100",
            "FEED_TIMEOUT_SECONDS": "60",
            "HTTP_TIMEOUT_SECONDS": "30",
        },
        "observability": {"enabled": True, "head_sampling_rate": 1.0},
        "d1_databases": [
            {
                "binding": "DB",
                "database_name": f"{instance_id}-db",
                "database_id": database_id,
            }
        ],
        "vectorize": [
            {"binding": "SEARCH_INDEX", "index_name": f"{instance_id}-entries"}
        ],
        "ai": {"binding": "AI"},
        "queues": {
            "producers": [
                {"binding": "FEED_QUEUE", "queue": f"{instance_id}-feed-queue"},
                {"binding": "DEAD_LETTER_QUEUE", "queue": f"{instance_id}-feed-dlq"},
            ],
            "consumers": [
                {
                    "queue": f"{instance_id}-feed-queue",
                    "max_batch_size": 5,
                    "max_batch_timeout": 30,
                    "max_retries": 3,
                    "dead_letter_queue": f"{instance_id}-feed-dlq",
                    "retry_delay": 300,
                }
            ],
        },
        "triggers": {"crons": ["0 * * * *"]},
    }

    # Write as JSONC with comments
    wrangler_path = PROJECT_ROOT / f"wrangler.{instance_id}.jsonc"

    # Manual JSONC formatting for readability
    jsonc_content = f"""// wrangler.{instance_id}.jsonc
// Planet instance: {name}
// Generated by create_instance.py
//
// Before deploying:
// 1. Create D1 database: npx wrangler d1 create {instance_id}-db
// 2. Update database_id below with the ID from step 1
// 3. Create Vectorize index: npx wrangler vectorize create {instance_id}-entries --dimensions 768 --metric cosine
// 4. Create queues:
//    npx wrangler queues create {instance_id}-feed-queue
//    npx wrangler queues create {instance_id}-feed-dlq
// 5. Set secrets:
//    npx wrangler secret put GITHUB_CLIENT_ID --config wrangler.{instance_id}.jsonc
//    npx wrangler secret put GITHUB_CLIENT_SECRET --config wrangler.{instance_id}.jsonc
//    npx wrangler secret put SESSION_SECRET --config wrangler.{instance_id}.jsonc
// 6. Run migrations: npx wrangler d1 execute {instance_id}-db --file migrations/001_initial.sql
// 7. Deploy: npx wrangler deploy --config wrangler.{instance_id}.jsonc

{json.dumps(config, indent=2)}
"""

    wrangler_path.write_text(jsonc_content)
    return wrangler_path


def run_wrangler_command(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run a wrangler command."""
    full_cmd = ["npx", "wrangler"] + cmd
    print(f"  Running: {' '.join(full_cmd)}")
    return subprocess.run(full_cmd, capture_output=True, text=True, check=check)


def provision_cloudflare_resources(instance_id: str, auto_provision: bool = False) -> dict:
    """Provision Cloudflare resources for the instance.

    Returns dict with resource IDs if auto_provision is True.
    """
    resources = {}

    if not auto_provision:
        print("\n📋 Manual provisioning steps:")
        print(f"\n  # 1. Create D1 database")
        print(f"  npx wrangler d1 create {instance_id}-db")
        print(f"\n  # 2. Create Vectorize index")
        print(
            f"  npx wrangler vectorize create {instance_id}-entries --dimensions 768 --metric cosine"
        )
        print(f"\n  # 3. Create queues")
        print(f"  npx wrangler queues create {instance_id}-feed-queue")
        print(f"  npx wrangler queues create {instance_id}-feed-dlq")
        print(f"\n  # 4. Set secrets")
        print(
            f"  npx wrangler secret put GITHUB_CLIENT_ID --config wrangler.{instance_id}.jsonc"
        )
        print(
            f"  npx wrangler secret put GITHUB_CLIENT_SECRET --config wrangler.{instance_id}.jsonc"
        )
        print(
            f"  npx wrangler secret put SESSION_SECRET --config wrangler.{instance_id}.jsonc"
        )
        print(f"\n  # 5. Run migrations")
        print(
            f"  npx wrangler d1 execute {instance_id}-db --file migrations/001_initial.sql --config wrangler.{instance_id}.jsonc"
        )
        print(f"\n  # 6. Deploy")
        print(f"  npx wrangler deploy --config wrangler.{instance_id}.jsonc")
        return resources

    print("\n🚀 Auto-provisioning Cloudflare resources...")

    # Create D1 database
    print("\n  Creating D1 database...")
    result = run_wrangler_command(["d1", "create", f"{instance_id}-db"], check=False)
    if result.returncode == 0:
        # Parse database ID from output
        for line in result.stdout.split("\n"):
            if "database_id" in line:
                # Extract UUID
                match = re.search(
                    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
                    line,
                )
                if match:
                    resources["database_id"] = match.group(0)
                    print(f"    ✓ Database created: {resources['database_id']}")
    else:
        print(f"    ✗ Failed to create database: {result.stderr}")

    # Create Vectorize index
    print("\n  Creating Vectorize index...")
    result = run_wrangler_command(
        [
            "vectorize",
            "create",
            f"{instance_id}-entries",
            "--dimensions",
            "768",
            "--metric",
            "cosine",
        ],
        check=False,
    )
    if result.returncode == 0:
        resources["vectorize_index"] = f"{instance_id}-entries"
        print(f"    ✓ Vectorize index created")
    else:
        print(f"    ✗ Failed to create Vectorize index: {result.stderr}")

    # Create queues
    print("\n  Creating queues...")
    for queue in [f"{instance_id}-feed-queue", f"{instance_id}-feed-dlq"]:
        result = run_wrangler_command(["queues", "create", queue], check=False)
        if result.returncode == 0:
            print(f"    ✓ Queue created: {queue}")
        else:
            print(f"    ✗ Failed to create queue {queue}: {result.stderr}")

    return resources


def main():
    parser = argparse.ArgumentParser(
        description="Create a new Planet instance",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive mode (prompts for all values)
  python scripts/create_instance.py

  # Quick setup with defaults
  python scripts/create_instance.py --id planet-python --name "Planet Python"

  # Full specification
  python scripts/create_instance.py \\
    --id planet-python \\
    --name "Planet Python" \\
    --description "Python community feed aggregator" \\
    --url "https://planetpython.org" \\
    --owner-name "Python Software Foundation" \\
    --owner-email "planet@python.org" \\
    --theme default

  # Auto-provision Cloudflare resources (requires wrangler auth)
  python scripts/create_instance.py --id planet-python --name "Planet Python" --auto-provision
""",
    )

    parser.add_argument("--id", help="Instance ID (e.g., planet-python)")
    parser.add_argument("--name", help="Display name (e.g., Planet Python)")
    parser.add_argument("--description", help="Description/tagline")
    parser.add_argument("--url", help="Public URL")
    parser.add_argument("--owner-name", help="Owner/organization name")
    parser.add_argument("--owner-email", help="Contact email")
    parser.add_argument(
        "--theme",
        choices=["default", "classic", "dark", "minimal"],
        default="default",
        help="Theme to use (default: default)",
    )
    parser.add_argument(
        "--auto-provision",
        action="store_true",
        help="Automatically create Cloudflare resources (requires wrangler)",
    )

    args = parser.parse_args()

    print("🌍 Planet Instance Creator")
    print("=" * 40)

    # Interactive mode if no ID provided
    if not args.id:
        print("\nEnter instance details (press Enter for defaults):\n")
        args.id = input("Instance ID [planet]: ").strip() or "planet"
        args.name = input(f"Display name [{args.id.replace('-', ' ').title()}]: ").strip()
        if not args.name:
            args.name = args.id.replace("-", " ").title()

    # Derive defaults from name if not provided
    slug = slugify(args.name) if args.name else args.id
    if not args.description:
        args.description = f"Feed aggregator for {args.name}"
    if not args.url:
        args.url = f"https://{slug}.example.com"
    if not args.owner_name:
        args.owner_name = args.name
    if not args.owner_email:
        args.owner_email = f"planet@{slug}.example.com"

    print(f"\n📝 Creating instance: {args.name}")
    print(f"   ID: {args.id}")
    print(f"   URL: {args.url}")
    print(f"   Theme: {args.theme}")

    # Create instance config
    config_path = create_instance_config(
        instance_id=args.id,
        name=args.name,
        description=args.description,
        url=args.url,
        owner_name=args.owner_name,
        owner_email=args.owner_email,
        theme=args.theme,
    )
    print(f"\n✓ Created instance config: {config_path.relative_to(PROJECT_ROOT)}")

    # Provision or print instructions
    resources = provision_cloudflare_resources(args.id, args.auto_provision)

    # Generate wrangler config
    database_id = resources.get("database_id", "YOUR_DATABASE_ID")
    wrangler_path = generate_wrangler_config(
        instance_id=args.id,
        name=args.name,
        description=args.description,
        url=args.url,
        owner_name=args.owner_name,
        owner_email=args.owner_email,
        theme=args.theme,
        database_id=database_id,
    )
    print(f"\n✓ Created wrangler config: {wrangler_path.relative_to(PROJECT_ROOT)}")

    if database_id == "YOUR_DATABASE_ID":
        print(
            f"\n⚠️  Update database_id in {wrangler_path.name} after creating the D1 database"
        )

    print("\n✅ Instance created successfully!")
    print(f"\nNext steps:")
    print(f"  1. Edit {config_path.relative_to(PROJECT_ROOT)} to configure admins")
    print(f"  2. Follow provisioning steps above (or in {wrangler_path.name})")
    print(f"  3. Deploy: npx wrangler deploy --config {wrangler_path.name}")


if __name__ == "__main__":
    main()
